config/routes.rb
Rails.application.routes.draw do
  get '/', to: "flats#index"
  get '/flats/:id', to: "flats#show", as: :flat
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require 'open-uri'
require 'json'

class FlatsController < ApplicationController
  before_action :set_flats
  
  def index
  end

  def show
    raise
    @flat = @flats.select { |flat| flat['id'] == params[:id].to_i}[0]
  end

  private

  def set_flats
    url='https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json'
    @flats=JSON.parse(open(url).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>
<% @flats.each do |flat| %>
  <div>
    <h2><%= flat['name']%></h2>
    <%= flat['price'] %> SEK
    <%= link_to "See more", flat_path(flat['id']) %>
  </div>
<% end %>

app/views/flats/show.html.erb
<h1><%= @flat['name'] %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStaticLivecode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>